version: '3'

services:
  gwt-app:
    image: 'gwt-app:latest'
    build:
      context: .
    container_name: gwt-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres

  postgres:
    image: 'postgres:14'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres